demo:
  kafka:
    bootstrap-servers: "http://localhost:9092"
    schema.registry.url: "http://localhost:8081"
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    key.serializer: org.apache.kafka.common.serialization.StringSerializer

    topic: "demo_topic"
